### PR TITLE
Safari 9 styles

### PR DESCRIPTION
**Pull request by roblan**
Styles mimicking new QuickTime plugin look

### CODE REVIEW

**Comment by hoyois** [comment]
Thanks! Any idea why the corners in the source selector are not properly rounded?

**Comment by roblan** [comment]
Looks like -webkit-backdrop-filter doesn't respect border-radius.  I haven't found a fix for that.

CTPlogoContainer doesn't look like it should either (I thought that changing placeholder.innerHTML in main.js:249 should add it there...)

**Comment by hoyois** [comment]
OK, thanks. I will try to investigate this a bit more: the floating controls on fullscreen videos have properly rounded corners. Let me know if you have any ideas.

**Comment by hoyois** [comment]
Ah, looks like they use a clip-path property to cut the corners out.

**Comment by roblan** [comment]
Can't wait for release :)

**Pull request merged**
